services:
  db:
    image: postgres:16-alpine
    container_name: diary_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - diary_postgres_data:/var/lib/postgresql/data # 🌟 Cambiado a un nombre único
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - diary_internal

  web:
    build: .
    container_name: diary_web
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - /var/www/diario_static:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    networks:
      - diary_internal
      - artdance_network

volumes:
  diary_postgres_data: # 🌟 Nombre único e independiente para este cofre secreto

networks:
  diary_internal: 
  artdance_network:
    external: true