# Generated by Django 6.0.6 on 2026-06-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='text',
        ),
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.AddField(
            model_name='card',
            name='text_encrypted',
            field=models.TextField(db_column='text', default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='title_encrypted',
            field=models.TextField(db_column='title', default=1),
            preserve_default=False,
        ),
    ]
