# Generated by Django 6.0.6 on 2026-06-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_card_text_remove_card_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyanswer',
            name='text_if_selected',
            field=models.TextField(blank=True, help_text='Texto que se mostrará si el usuario selecciona esta respuesta (opcional)', null=True),
        ),
    ]
